name: Générer le RSS FFTA

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  generate-rss:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Générer le RSS
        env:
          BROWSERLESS_TOKEN: ${{ secrets.BROWSERLESS_TOKEN }}
        run: |
          python generate-rss.py

      - name: Vérifier le fichier RSS
        run: |
          echo "Contenu de ffta.xml :"
          cat ffta.xml

      - name: Enregistrer le RSS dans GitHub
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add ffta.xml

          if git diff --cached --quiet; then
            echo "Aucune modification du RSS."
          else
            git commit -m "Mise à jour du flux RSS FFTA"
            git push
          fi
